### ISSUE TITLE
Grammar to Pratt-Parser

### ISSUE THREAD

**Issue by asteding** [matklad/minipratt#4]
Hello @matklad 

i really loved your article about writing the mini pratt-parser. 
What I struggled with is how would you write a formal grammar e.g.

```
Expr ::=
    Expr '+' Expr
  | Expr '*' Expr
  | '(' Expr ')'
  | 'number'
```
and or 
```
Expr ::=
    Factor
  | Expr '+' Factor

Factor ::=
    Atom
  | Factor '*' Atom

Atom ::=
    'number'
  | '(' Expr ')'
```

into a "full grammar"? Like adding if/else/for/while (either as statements or expressions etc)
Would you mind explaining a bit more, I'd appreciate it a lot! 

Thanks and all the best to you.

**Comment by matklad** [comment]
Hey, I don't have time to dig deeper into the topic at the moment, so the best way is probably to refer to the books on the topic. 

https://compilers.iecc.com/crenshaw/ is an example of a lesser known one, but which is really great and highly recommended.

**Comment by asteding** [comment]
Hello @matklad 
no problem. Please keep up the awesome work for rust-analyzer :)
Thank you very much for the link I'll go have a read. If you think my question is worth a blog post I'd also appreciate it a lot.
Have a good time and I also closed the issue.

Best regards.
