### ISSUE TITLE
Haskell-style function call syntax, without currying

### ISSUE THREAD

**Issue by lunacookies** [matklad/minipratt#5]
Hi,

I used your article to implement a Pratt parser for the programming language I’m working on. The syntax for a function call in my language is as follows:

```haskell
f a b c
```

This is very similar to Haskell. I would like for function application to have a higher binding power than other operations:

```haskell
sin 90 * 2 == (sin 90) * 2
```

This would be easy to implement if I treated whitespace as a binary operator with a high binding power. However, this only makes sense with currying:

```haskell
f a b c == ((f a) b) c
```

Without currying, whitespace can no longer be treated as a binary operator.

How can I implement the behaviour I described above, but without adding currying to my language?

**Comment by matklad** [comment]
It's not exactly treating whitespace as an operator. Rather, in this match:

https://github.com/matklad/minipratt/blob/a9586ef0a659993d56874cde7cce20249cd8da78/src/bin/pratt.rs#L87-L91

you'll need to check if the non-op token can begin an expression, and treat it as a virtual operator

```rust
        let op = match lexer.peek() {
            Token::Op(op) => op,
            Token::Ident | Token::LefetParen | ... => Application
            Token::Eof | Token::RightParen | ... => break,
            t => panic!("bad token: {:?}", t),
        };
```

**Comment by lunacookies** [comment]
Sorry to bother you – don’t worry about this if you don’t have time :)

I’ve spent the past few days trying to make this work. After a few convoluted attempts, I managed to hack together [an ugly implementation](https://github.com/arzg/fjord/blob/ba7e897851f6f861b0e7d5dd266ba43b8f17a109/src/parser/expr.rs#L15) that works fine with function calls that have only one parameter. However, when you give it a function call with multiple parameters (e.g. `f a b c`), it parses it as if the language had currying (i.e. `((f a) b) c`).

How can I make it parse function calls that have more than one parameter, but with parameters as siblings instead of the curried form?

Also, as an aside, how should I handle bare words? My language is a shell, so, although I don’t like bare words, I pretty much have to include them (imagine running `ls "-l" "~/Desktop"`!). Due to my dislike of bare words, I’d like to limit their usage as much as possible, only allowing it when it dramatically reduces typing. I’ve settled on only allowing them in function parameters. Should I apply this restriction during parsing, or during AST validation afterwards?

**Comment by lunacookies** [comment]
I have finally solved it! [Here](https://github.com/arzg/fjord/compare/attempt-pratt-function-call)’s the diff of what I’ve done to make this work in case you’re interested.

**Comment by matklad** [comment]
Nice! Thanks for linking in the diff, I bet it'll be useful to some!
